# Generated by Django 6.0 on 2026-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_user_is_email_verified_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
