# Generated by Django 6.0 on 2026-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_by',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
