# Generated by Django 6.0 on 2026-01-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_deleted_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_0ace22_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
