# Generated by Django 5.2.10 on 2026-01-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0002_organization_user_is_email_verified_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_task_id_4c61a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_user_id_8613ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_owner_i_11d805_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_assigne_462a05_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskhistory',
            name='tasks_histo_task_id_fb6619_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskhistory',
            name='tasks_histo_actor_i_3a2fb8_idx',
        ),
        migrations.AddField(
            model_name='comment',
            name='organization',
            field=models.ForeignKey(default='0978b4ea-b45f-4da9-9887-991b586d6068', on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='users.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(default='0978b4ea-b45f-4da9-9887-991b586d6068', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='organization',
            field=models.ForeignKey(default='0978b4ea-b45f-4da9-9887-991b586d6068', on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='users.organization'),
            preserve_default=False,
        ),
    ]
