# Generated by Django 6.0 on 2026-01-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_status_426d4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_status_b44b4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_is_proc_90680c_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_event_t_54b761_idx',
        ),
    ]
