name: Debug Logs
on:
  push:
    branches: [debug-logs]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Get Logs
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/taskvault-backend
            sudo docker compose logs --tail=100 web nginx
